name: fyp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  easy_search_bar: ^2.4.2
  carousel_slider: ^4.2.1
  http: ^0.13.5
  fluttertoast: ^8.1.3
  shared_preferences: ^2.0.17
  connectivity: ^3.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
